# Generated by Django 3.0 on 2019-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
            ],
        ),
    ]
