# Generated by Django 3.0 on 2019-12-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addjob',
            old_name='contact',
            new_name='approach',
        ),
    ]
