# Generated by Django 3.0 on 2019-12-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191221_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddJob',
            new_name='Jobs',
        ),
    ]
