# Generated by Django 3.0 on 2019-12-22 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20191221_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='postdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
