# Generated by Django 3.0 on 2019-12-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='postdate',
            field=models.DateField(),
        ),
    ]
