# Generated by Django 3.0 on 2019-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20191222_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='domain',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
