# Generated by Django 3.0 on 2019-12-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='domain',
        ),
    ]
